# Generated by Django 2.2.8 on 2021-12-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shinigami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellido')),
                ('shikai', models.CharField(max_length=80)),
                ('bankai', models.CharField(max_length=80)),
            ],
        ),
    ]
